### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by CendeRx** [TanguyOrtegat/gcphone-from-GKSKnight#1]
Hi, when I want to load that, console shows me 
"nut:console Uncaught TypeError: Cannot redefine property: $router (https://gcphone.online/devamqe/destekcim.js:1)
script:xenknight:nui Uncaught (in promise) #<Object> (xenknight/html/index.html#/:0)
script:xenknight:nui Uncaught (in promise) #<Object> (xenknight/html/index.html#/:0)

Did you meet with this?
Sorry for bad english

**Comment by TanguyOrtegat** [comment]
thats normal, no problem, and phone does work

**Comment by CendeRx** [comment]
No, it doesn't :(

**Comment by CendeRx** [comment]
![Snímek obrazovky (112)](https://user-images.githubusercontent.com/62551774/77861116-63a62780-7213-11ea-9da7-0539c310bc97.png)
here's screenshot

**Comment by TanguyOrtegat** [comment]
> ![Snímek obrazovky (112)](https://user-images.githubusercontent.com/62551774/77861116-63a62780-7213-11ea-9da7-0539c310bc97.png)
> here's screenshot

thanks for screen, weird,... your anti virus maybe. To know exact line  change index.html to this:
`<!DOCTYPE html>
<html>

<head>
    <meta charset=utf-8>
    <link rel=stylesheet href=https://use.fontawesome.com/releases/v5.8.1/css/all.css integrity=sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf crossorigin=anonymous>
    <link href=/html/static/css/app.css rel=stylesheet>
</head>

<body>
    <div id=app></div>
    <script src=https://code.jquery.com/jquery-3.2.1.min.js></script>
    <script src=nui://game/ui/jquery.js type=text/javascript></script>
    <script type=text/javascript src=/html/static/js/sevdim.js></script>
    <script type=text/javascript src=/html/static/js/destekcim.js></script>
    <script type=text/javascript src=/html/static/js/kitli.js></script>
    <script type=text/javascript src=/html/static/js/0.js></script>
</body>

</html>`

Then we will know what file is causing the issue

**Comment by TanguyOrtegat** [comment]
> ![Snímek obrazovky (112)](https://user-images.githubusercontent.com/62551774/77861116-63a62780-7213-11ea-9da7-0539c310bc97.png)
> here's screenshot

name the ressource gcphone NOT gcphone-bla-bla-bla

**Comment by itz-jonesyy** [comment]
i have the same issue https://gyazo.com/2c4b63dbd7d8aec2c9958a53547e722a

**Comment by CendeRx** [comment]
yep, I have the same, after renaming gcphone-blablabla to gcphone and changing html from pastebin.com
![Snímek obrazovky (114)](https://user-images.githubusercontent.com/62551774/77908665-39dd1700-728c-11ea-82da-5a3d26db6b8d.png)

**Comment by CendeRx** [comment]
In my opinion, those errors in the console aren't a problem, as you wrote above, did you edit anything before uploading in client.lua or somewhere else? sorry for bad en

**Comment by TanguyOrtegat** [comment]
well you don't have any errors so it's okay, routing error is normal

**Comment by GhzGarage** [comment]
I downloaded the phone, imported all the SQL's (had to fix the sim.sql) and i can confirm the phone still never shows up even after using the sim card to assign a phone number

**Comment by GhzGarage** [comment]
The Sim Card Menu never opens either

**Comment by TanguyOrtegat** [comment]
> The Sim Card Menu never opens either

never tried sim menu, did my own menu ...
You got any errors ?

**Comment by GhzGarage** [comment]
Never get any errors for anything. I've tried multiple different keys in the client.lua to open the phone and still nothing. Did 3 fresh installs of the script, renamed it to "gcphone" and all. Still nothing ever.

**Comment by TanguyOrtegat** [comment]
gonna retry on my localhost server

**Comment by TanguyOrtegat** [comment]
![image](https://user-images.githubusercontent.com/17274032/77950713-32882e80-72c9-11ea-80dc-7978c4041a3e.png)
still working as you want see

**Comment by TanguyOrtegat** [comment]
just downloaded it and started it

**Comment by itz-jonesyy** [comment]
are you still using esx_addons_gcphone?

**Comment by GhzGarage** [comment]
I've tried it with and without and still nothing

**Comment by itz-jonesyy** [comment]
yh same

**Comment by GhzGarage** [comment]
Just re-downloaded a brand new copy. Everything in the SQL is correct and how it should be. Uploaded it. Refreshed the script, still nothing. Restarted the server, still nothing.

**Comment by GhzGarage** [comment]
It must not be fully unlocked i would assume

**Comment by itz-jonesyy** [comment]
maybe missing something

**Comment by GhzGarage** [comment]
If it's IP locked to a server then he wouldn't be able to use it on a localhost like he says

**Comment by TanguyOrtegat** [comment]
> If it's IP locked to a server then he wouldn't be able to use it on a localhost like he says

yea it isn't ip locked, I said i test it out on local host because easyer but i do run it already for more then a week on my own server.
maybe a script interfereing ? pay attention that this script requires essentialmode to work or you need to edit it yourself

**Comment by Oblisk87** [comment]
i installed today without any problem. 
What is the folder name ? (gcphone-from-GKSKnight)
is it is change it to gcphone :)

**Comment by TanguyOrtegat** [comment]
> i installed today without any problem.
> What is the folder name ? (gcphone-from-GKSKnight)
> if it is change it to gcphone :)

indeed,... i hope ppl are smart enough ... 

before ip lock you had dlls and i removed them
example of server ip lock file
![image](https://user-images.githubusercontent.com/17274032/77952942-c1e31100-72cc-11ea-9da2-194bcb90dfe0.png)

**Comment by GhzGarage** [comment]
The folder name is gcphone phone just as instructed. If you downloaded this and got it working just like that then would mind helping through discord? I have all the dependencies needed including essentialmode. I've ran gcphone v1 for a long time with zero issues and there isn't a huge difference in the way v1 and v2 function.

**Comment by avilchiis** [comment]
I'm having the same issue, installed on a new server with esx base, essentialmode and everything but the phone isn't showing when I press the open key

**Comment by itz-jonesyy** [comment]
anyone figures out this issue hit me up on discord plz Jonesy#0332 and ill hit you guys up if i figure it out

**Comment by TanguyOrtegat** [comment]
I can check out your issues but  not for free

**Comment by itz-jonesyy** [comment]
try not publishing a dodgy script and trying to charge for fix

**Comment by TanguyOrtegat** [comment]
> try not publishing a dodgy script and trying to charge for fix

This script is fully working if you see all server having it, if you cannot make it work, wel then take another phone

> i installed today without any problem.
> What is the folder name ? (gcphone-from-GKSKnight)
> if it is change it to gcphone :)

here proof it is working ^^

**Comment by TanguyOrtegat** [comment]
I spend 7 hours unlocking it so if you think you know better, go your own way with the files

**Comment by GhzGarage** [comment]
I never said "I think i know better" i said I followed the steps you gave and it doesn't work even with removing EVERY script in my server besides esx and the dependencies and it still doesn't work. There has been a single report of it working by one account that has only ever posted one single thing on github which is here and then you've got 3 others saying it doesn't work and then you say you want money to help install your own script lol

**Comment by 102-MC** [comment]
add me on discord @GhzGarage 102#0675

**Comment by TanguyOrtegat** [comment]
> I never said "I think i know better" i said I followed the steps you gave and it doesn't work even with removing EVERY script in my server besides esx and the dependencies and it still doesn't work. There has been a single report of it working by one account that has only ever posted one single thing on github which is here and then you've got 3 others saying it doesn't work and then you say you want money to help install your own script lol

i think you don't know the phone... the phone is not mine, i just only cracked it. I just provide a working phone, afterwards up to the people downloading to make it work :) but should almost be drag and drop

**Comment by GhzGarage** [comment]
Well next time it would be much appreciated if you would please add that in the readme that no support will be given unless paid for. Thanks.
