### ISSUE TITLE
cant run it ! i have error

### ISSUE THREAD

**Issue by ShadowOfVoid** [TanguyOrtegat/gcphone-from-GKSKnight#11]
i get the error : Caanot redefine property: $reouter (@gcphone/html/static/js/destekcim.js:1) what should i do ?

**Comment by TanguyOrtegat** [comment]
That error is normal. Because he cant check ip.  But script is working

**Comment by DanyCryEn** [comment]
when i try to take a picture my screen freezes in the camera screen.... and i have to restart the resource.

**Comment by TanguyOrtegat** [comment]
> when i try to take a picture my screen freezes in the camera screen.... and i have to restart the resource.

You need to have picture server

**Comment by DanyCryEn** [comment]
i know... and i have, i think....
i don't have anymore error for screenshot-basic.

**Comment by DanyCryEn** [comment]
> > when i try to take a picture my screen freezes in the camera screen.... and i have to restart the resource.
> 
> You need to have picture server

i know... and i have, i think....
i don't have anymore error for screenshot-basic.

**Comment by DanyCryEn** [comment]
i've image-server too ... run on port 3555 . but i can't take a picture..

**Comment by DanyCryEn** [comment]
> > when i try to take a picture my screen freezes in the camera screen.... and i have to restart the resource.
> 
> You need to have picture server

this is what happened when i take a picture
[https://ibb.co/KhRY8jm](url)
