### ISSUE TITLE
Cant open the phone

### ISSUE THREAD

**Issue by DevVladyslav** [TanguyOrtegat/gcphone-from-GKSKnight#2]
Same issue as the other individual was having, cant open da phone.

**Comment by TanguyOrtegat** [comment]
well phone is working, so maybe you did something wrong ? you checked controlpressed keys ? maybe another script interfering?

**Comment by TanguyOrtegat** [comment]
> ![Snímek obrazovky (112)](https://user-images.githubusercontent.com/62551774/77861116-63a62780-7213-11ea-9da7-0539c310bc97.png)
> here's screenshot

name the ressource gcphone NOT gcphone-bla-bla-bla
