### ISSUE TITLE
Remove @xenknight#2795 Cracked in the bank app.

### ISSUE THREAD

**Issue by Oblisk87** [TanguyOrtegat/gcphone-from-GKSKnight#4]
Is there a way remove it ?

**Comment by TanguyOrtegat** [comment]
do it yourself :)

**Comment by Oblisk87** [comment]
Cant Encrypted files

**Comment by TanguyOrtegat** [comment]
well then too bad :)

**Comment by Oblisk87** [comment]
your the one that encrypted them xD? so help please

**Comment by TanguyOrtegat** [comment]
there were already encrypted, i did nothing

**Comment by TanguyOrtegat** [comment]
i just did some reverse engineering to unlock it

**Comment by Oblisk87** [comment]
Oke. thanks anyway :)

**Comment by TanguyOrtegat** [comment]
cheers no problem mate

**Comment by CendeRx** [comment]
Did you solve it? I am trying to remove it, but I can't find it anywhere...

**Comment by TanguyOrtegat** [comment]
i can but aint free
