### ISSUE TITLE
gcphone error

### ISSUE THREAD

**Issue by delsolsi** [TanguyOrtegat/gcphone-from-GKSKnight#6]
everything is installed fine all sqls loaded just fine and getting this error

https://gyazo.com/81992e685f8d6228132c1c05be0fc066

**Comment by Caspersosa** [comment]
Same here.u know the fix ?

**Comment by delsolsi** [comment]
no but this one actually works https://drive.google.com/file/d/1rr1u4Alg1Q2cKTSGeYhGCLRv4eKb6KzD/view

**Comment by TanguyOrtegat** [comment]
repaired the check phone thanks

**Comment by delsolsi** [comment]
thanks bud, but shouldntit be toggle instead of toogle?

**Comment by TanguyOrtegat** [comment]
no function is named like that

**Comment by delsolsi** [comment]
ah ok then all good, i ll test later thanks.
