### ISSUE TITLE
Buggy

### ISSUE THREAD

**Issue by Kimsjoberg99** [TanguyOrtegat/gcphone-from-GKSKnight#7]
is this even fully completed? kinda buggy, sometimes buttons wont work, sometimes my inventory starts to freeze etc - my other gcphone works fine tho so ive tried a few things

**Comment by Kimsjoberg99** [comment]
And Jager Bom [dev]#2795 isnt a proper discord, cant find him atleast

**Comment by BBLJB** [comment]
When trying to take pictures, you get stuck. Doesn't send anything in twitter nor instagram.

**Comment by TanguyOrtegat** [comment]
yes you need to host your own pictures or find a picture host.

phone is working without any issues

**Comment by Kimsjoberg99** [comment]
Hmm, my other gcphone works perfectly. I've tried everything to fix things to be smooth. The phone is slow sometimes, 2/10 times the twitter/instagram doesnt work or even shows the message. Weird

**Comment by Kimsjoberg99** [comment]
You use another version or the same as u uploaded?

**Comment by Oblisk87** [comment]
@Kimsjoberg99 I got the same problem thats why i buyed the full version of this phone. Its craked realy badly lots of bugs. 

The real deal is working fine :)

**Comment by Kimsjoberg99** [comment]
I won't pay for a script lol. @Oblisk87
